use student;
SELECT * FROM STUDENTS;

SELECT COUNT(STU_FNAME)FROM STUDENTS;

SELECT DISTINCT STU_CITY  
FROM students;

SELECT * FROM STUDENTS;

SELECT DISTINCT CITY  
FROM students;

UPDATE STUDENTS  
SET STU_FNAME = 'Priya'   
WHERE ID = '2';  

SELECT STU_FNAME FROM STUDENTS  
GROUP BY STU_FNAME;  

SELECT * FROM STUDENTS;

SELECT COUNT(ID), CITY
FROM STUDENTS
GROUP BY CITY
ORDER BY COUNT(ID) DESC;

SELECT CITY ,ID
FROM STUDENTS
WHERE CITY = 'Lyon';

SELECT COUNT(ID), CITY
FROM STUDENTS
GROUP BY CITY
HAVING COUNT(ID) < 4;


CREATE TABLE clg_master (
   clg_id int NOT NULL,
    UNIVERSITY VARCHAR(255),
    PRIMARY KEY (clg_id),
    FOREIGN KEY (UNIVERSITY) REFERENCES STUDENTS(UNIVERSITY)
);
show tables;

SELECT ASCII(STU_FNAME) AS Name
FROM STUDENTS; 

SELECT CHAR_LENGTH("Priya") AS LengthOfString; 

select char_length(STU_LNAME) AS LENGTHOF_LNAME
FROM STUDENTS;

select CONCAT("HELLO", "WORLD") AS CONCATENATED;

SELECT CONCAT(EMAIL, " ", CONTACT, " ") AS INFO
FROM STUDENTS; 

 SELECT FIND_IN_SET("s", "s,q,l");
 
SELECT INSERT("MYSQL.com", 1, 5, "Example"); 

